name : hillelarnold.com
brand : hillelarnold.com
description : True as the average.
keyword : music, archives
url : http://hillelarnold.com
email : hillel@hillelarnold.com
twitter : helrond
github : helrond
author : Hillel Arnold
analytics : UA-35698968-1
year : 2016
markdown : kramdown
permalink: blog/:year/:month/:title/
exclude :
  - node_modules
plugins:
  - jekyll-sitemap
